[package]
authors = ["aarbuzov"]
name = "zmodem"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
rust-version = "1.73"

[dependencies]
clap = "2.21.1"
crc = "3.0.1"
env_logger = "0.4.2"
hex = "0.2.0"
log = "0.3.7"
rstest = "0.18.2"
strum = { version = "0.25.0", features = ["strum_macros"] }
strum_macros = "0.25.3"
zerocopy = { version = "0.7.26", features = ["derive"] }

[dev-dependencies]
lazy_static = "1"
rand = "0.3.15"
